### ISSUE TITLE
Add automatic build and links to the downloadable images

### ISSUE THREAD

**Issue by fedorov** [dockbuild/dockbuild#14]
@thewtex @jcfr do you have this set up somewhere already? I could not find them under docker hub dockcross.

**Comment by fedorov** [comment]
found it https://hub.docker.com/u/centosbuild/. Any particular reason why those are not under the dockcross org?

**Comment by thewtex** [comment]
I think the reasoning was to keep the image name shorter. But maybe it will be easier to find by putting them in the `dockcross` organization. @jcfr what do you think?

**Comment by jcfr** [comment]
> Any particular reason why those are not under the dockcross org?

dockcross hosts images used for cross-compilation. The centosbuild are a  different in the sens they do not define a toolchain.

The code is hosted of the `dockcross` org out of convenience. I have also been thinking about a `dockbuild` organization. Would that be better ? 

Otherwise, the name of images is outlined in the README: https://github.com/dockcross/centos-build#maintained-images

**Comment by fedorov** [comment]
In my view, it is just easier to find things when organization on github maps to the one on docker hub. Sorry for missing the reference in README, maybe that happened because it doesn't mention docker hub. It makes sense now, I am fine either way.

**Comment by jcfr** [comment]
Github organization/project and  dockerhub organization are now consistently named.

See https://github.com/dockbuild/dockbuild and https://hub.docker.com/u/dockbuild/
