### ISSUE TITLE
Cant add include folders 

### ISSUE THREAD

**Issue by makorne** [dockbuild/dockbuild#59]
I added includes folder to work dir (C++), it is requested like this
#include <includes/file.h> in many files
I added include_directories("/work/includes") in CMakeLists.txt
But compilation terminated. fatal error: includes/file.h: No such file or directory

How to add include folders?
Thanks!

**Comment by jcfr** [comment]
Thanks for reporting the issue :+1: 

To better assist you, would you have a small example of project to share along with the command used to configure it ?

**Comment by makorne** [comment]
cd ~/dockerbuild
mkdir ~/include 
cp  /usr/include/jpeglib.h ~/dockerbuild/include/

example.cxx :
```
#include <iostream>
#include <include/jpeglib.h>

int main( int argc, char * argv[] )
{
  std::cout << "Hello cross-compilation world!" << std::endl;
  return 0;
}
```
cMakeLists:
```
project(example-cxx)

include_directories("/work/include")

add_executable(example.cxx)
```

dockerbuild$ ./dockbuild-ubuntu1804-gcc7-latest bash -c '$CXX example.cxx -o example_cxx'
```
example.cxx:2:10: fatal error: include/jpeglib.h: No such file or directory
 #include <include/jpeglib.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by jcfr** [comment]
### Addressing the include issue

Since include directories are relative, you can address the problem in two ways:

* Approach 1: In `CMakeLists.txt`: `include_directories("/work/include")` -> `include_directories("/work")`
* Approach 2: In `example.cxx`: `#include <include/jpeglib.h>` -> `#include <jpeglib.h>`

That said, I suggest to avoid using absolute directory in your CMakeLists.txt, instead you could do this:

```
set(CMAKE_INCLUDE_CURRENT_DIR ON)
```

See https://cmake.org/cmake/help/latest/variable/CMAKE_INCLUDE_CURRENT_DIR.html

### Other comments

* Avoid using `include_directories()`

Moving forward, I also recommend against using `include_directories()`, instead you should consider associating include directories directly with targets:

```
[...]
add_executable(example)
target_include_directories(example PUBLIC relative/path/to)
```

See https://cmake.org/cmake/help/latest/command/target_include_directories.html

* Associating source with executable

Instead of `add_executable(example.cxx)`, you should do something like this:

```
add_executable(example example.cxx)
```

See https://cmake.org/cmake/help/latest/command/add_executable.html

**Comment by jcfr** [comment]
Finally, if you would like to link your executable against `jpeglib`, you would also have to make sure the library is either build in your project or available in the docker image.

**Comment by makorne** [comment]
Thank you very much for so detailed info!

But I tried all your variants... Nothing changed.
```
 fatal error: jpeglib.h: No such file or directory
 #include <jpeglib.h>
```
```
fatal error: include/jpeglib.h: No such file or directory
 #include <include/jpeglib.h>
          ^~~~~~~~~~~~~~~~~~~
```

**Comment by jcfr** [comment]
To better understand what is wrong, would you have an example to share ?

**Comment by jcfr** [comment]
Having an other look, it seems the command you added at the beginning of https://github.com/dockbuild/dockbuild/issues/59#issuecomment-483702058 are incorrect.

Instead of:

```
cd ~/dockerbuild
mkdir ~/include
cp /usr/include/jpeglib.h ~/dockerbuild/include/
```

you should probably do:

```
cd ~/dockerbuild
mkdir ~/dockerbuild/include
cp /usr/include/jpeglib.h ~/dockerbuild/include/
```

After you shell in the image, check that `/work/include` contains the header.

In the meantime, I am closing this issue. Feel free to create a new one if you still have problem.
